# 默认配置
# https://github.com/elastic/kibana/blob/master/src/dev/build/tasks/os_packages/docker_generator/templates/kibana_yml.template.js
#
server.name: kibana
server.host: '0'
elasticsearch.hosts: ['http://elasticsearch:9200']
xpack.monitoring.ui.container.elasticsearch.enabled: true

# X-Pack 设置
elasticsearch.username: elk
elasticsearch.password: change_me
